import { NextResponse } from "next/server";

const mockProducts = [
  {
    id: 1,
    name: "Handwoven Basket",
    description: "A beautifully handwoven basket made from sustainable natural fibers.",
    price: 45,
    category: "Home Decor",
    emoji: "🧺",
    materials: "Natural palm fibers",
    stock: 15,
    shippingTime: "3-5 business days",
    rating: 4.8,
    sellerId: 1,
    seller: { id: 1, name: "Maria G.", bio: "Basket artisan" },
    reviews: [],
  },
  {
    id: 2,
    name: "Ceramic Mug Set",
    description: "A charming set of handmade ceramic mugs.",
    price: 38,
    category: "Kitchen",
    emoji: "☕",
    materials: "Hand-fired ceramic",
    stock: 12,
    shippingTime: "2-4 business days",
    rating: 4.5,
    sellerId: 2,
    seller: { id: 2, name: "Javiera L.", bio: "Ceramic and textile artisan" },
    reviews: [],
  },
  {
    id: 3,
    name: "Knitted Scarf",
    description: "Soft, cozy handmade scarf.",
    price: 52,
    category: "Apparel",
    emoji: "🧣",
    materials: "Premium wool blend",
    stock: 8,
    shippingTime: "1-3 business days",
    rating: 5,
    sellerId: 3,
    seller: { id: 3, name: "Rony R.", bio: "Knitted apparel artisan" },
    reviews: [],
  },
  {
    id: 4,
    name: "Silver Leaf Ring",
    description: "Elegant sterling silver ring.",
    price: 29,
    category: "Jewelry",
    emoji: "💍",
    materials: "925 sterling silver",
    stock: 20,
    shippingTime: "3-7 business days",
    rating: 4.7,
    sellerId: 4,
    seller: { id: 4, name: "Ana P.", bio: "Jewelry artisan" },
    reviews: [],
  },
  {
    id: 5,
    name: "Watercolor Print",
    description: "Vibrant watercolor print.",
    price: 65,
    category: "Art & Prints",
    emoji: "🎨",
    materials: "Archival art paper",
    stock: 25,
    shippingTime: "2-5 business days",
    rating: 4.9,
    sellerId: 5,
    seller: { id: 5, name: "Carlos M.", bio: "Artist and illustrator" },
    reviews: [],
  },
  {
    id: 6,
    name: "Lavender Soap Bar",
    description: "Natural lavender soap.",
    price: 18,
    category: "Bath & Beauty",
    emoji: "🧼",
    materials: "Natural oils and lavender extract",
    stock: 40,
    shippingTime: "1-2 business days",
    rating: 4.6,
    sellerId: 6,
    seller: { id: 6, name: "Sofia R.", bio: "Natural beauty artisan" },
    reviews: [],
  },
  {
    id: 7,
    name: "Wooden Puzzle",
    description: "Handcrafted wooden puzzle.",
    price: 34,
    category: "Toys & Games",
    emoji: "🧩",
    materials: "Sustainably sourced wood",
    stock: 18,
    shippingTime: "2-4 business days",
    rating: 4.4,
    sellerId: 7,
    seller: { id: 7, name: "Pedro A.", bio: "Wood crafts artisan" },
    reviews: [],
  },
  {
    id: 8,
    name: "Macramé Wall Art",
    description: "Decorative macramé wall hanging.",
    price: 78,
    category: "Home Decor",
    emoji: "🪢",
    materials: "Cotton cord",
    stock: 10,
    shippingTime: "4-6 business days",
    rating: 4.8,
    sellerId: 8,
    seller: { id: 8, name: "Lucia V.", bio: "Macrame artisan" },
    reviews: [],
  },
  {
    id: 9,
    name: "Hand-dyed Tote Bag",
    description: "Reusable hand-dyed tote bag.",
    price: 42,
    category: "Apparel",
    emoji: "👜",
    materials: "Organic cotton",
    stock: 22,
    shippingTime: "2-4 business days",
    rating: 4.3,
    sellerId: 2,
    seller: { id: 2, name: "Javiera L.", bio: "Ceramic and textile artisan" },
    reviews: [],
  },
];

export async function GET() {
  return NextResponse.json(mockProducts);
}